pipeline {
    agent any
    stages {  
        stage('Deletando pasta DevOps') {
            steps {
                sh 'ssh $USER_SERVER@$HOST_SERVER "bash -s" < https://github.com/rafaelspaesleme-ads/developer-env/raw/master/src/scripts/Deletepipeline.sh'
            }
        }
        stage('Removendo restos') {
            steps {
                echo 'Dados excluidos com sucesso!'
            }
        }
    }   
    post {
        always {
            echo 'Executando retornos do job.'
        }
        success {
            echo 'Ambiente criado com sucesso!'
        }
        failure {
            echo 'Erro ao criar ambiente. Consulte o log da console.'
        }
        unstable {
            echo 'Este build demonstra instabilidade'
        }
        changed {
            echo 'Comandos alterados no pipeline... a verificar.'
            echo 'Builder em falha recuperado com sucesso!'
        }
    }
}