pipeline {
    agent any
    stages {
        stage('Removendo pacotes antigos') {
            steps {
                sh 'curl -sSL https://github.com/rafaelspaesleme-ads/dev-env/raw/master/src/scripts/Dlast.sh | sh'
            }
        }
        stage('Gerando acesso via SCP/SSH') {
            steps {
                timeout(time: 20, unit: 'SECONDS') {
                    sh 'curl -sSL https://github.com/rafaelspaesleme-ads/dev-env/raw/master/src/scripts/Gkey.sh | bash'
                }
            }
        }        
        stage('Criando ambiente DevOps') {
            steps {
                sh 'curl -sSL https://github.com/rafaelspaesleme-ads/dev-env/raw/master/src/scripts/Ienv.sh | bash'
            }
        }        
        stage('Transferindo dados para servidor') {
            steps {
                sh 'curl -sSL https://github.com/rafaelspaesleme-ads/dev-env/raw/master/src/scripts/Dsend.sh | bash'
            }
        }
        stage('Removendo restos') {
            steps {
                sh 'curl -sSL https://github.com/rafaelspaesleme-ads/dev-env/raw/master/src/scripts/Dpip.sh | sh'
            }
        }
    }   
    post {
        always {
            echo 'Executando retornos do job.'
        }
        success {
            echo 'Ambiente criado com sucesso!'
        }
        failure {
            echo 'Erro ao criar ambiente. Consulte o log da console.'
        }
        unstable {
            echo 'Este build demonstra instabilidade'
        }
        changed {
            echo 'Comandos alterados no pipeline... a verificar.'
            echo 'Builder em falha recuperado com sucesso!'
        }
    }
}
